// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6oGd98hBRE68pq5siVnulIFqjnC_gjBg',
    appId: '1:125129385603:web:9391df5029e6c16cfd1db6',
    messagingSenderId: '125129385603',
    projectId: 'e-ligtas-ccaed',
    authDomain: 'e-ligtas-ccaed.firebaseapp.com',
    storageBucket: 'e-ligtas-ccaed.appspot.com',
    measurementId: 'G-EWPMH7YY3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARk23xV-tFrTr3R-yByRjFZMA8bNbgS70',
    appId: '1:125129385603:android:eb91cf939e9a2109fd1db6',
    messagingSenderId: '125129385603',
    projectId: 'e-ligtas-ccaed',
    storageBucket: 'e-ligtas-ccaed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABuq8k4JTBKyA5QUwjOIMcp8qHES7Jdh0',
    appId: '1:125129385603:ios:00fe3fd2ace3324ffd1db6',
    messagingSenderId: '125129385603',
    projectId: 'e-ligtas-ccaed',
    storageBucket: 'e-ligtas-ccaed.appspot.com',
    iosBundleId: 'com.example.eligtasResident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABuq8k4JTBKyA5QUwjOIMcp8qHES7Jdh0',
    appId: '1:125129385603:ios:52513b70b6f637d6fd1db6',
    messagingSenderId: '125129385603',
    projectId: 'e-ligtas-ccaed',
    storageBucket: 'e-ligtas-ccaed.appspot.com',
    iosBundleId: 'com.example.eligtasResident.RunnerTests',
  );
}
